import Toybox.Lang;
import Toybox.Test;

// Generated by tools/synthetic_workout.py; do not edit.

(:test)
function testSyntheticStillMotionVector(logger as Test.Logger) as Boolean {
    var x = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] as Array<Number>;
    var y = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] as Array<Number>;
    var z = [
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000,
        1000
    ] as Array<Number>;
    var result = Motion.features(x, y, z);
    Test.assertEqualMessage(result[:rms] as Number, 1000, "still RMS matches independent oracle");
    Test.assertEqualMessage(result[:peak] as Number, 1000, "still peak matches independent oracle");
    Test.assertEqualMessage(result[:zc] as Number, 0, "still crossings match independent oracle");
    Test.assertEqualMessage(result[:dynamicRms] as Number, 0, "still dynamic RMS matches independent oracle");
    Test.assertEqualMessage(result[:dynamicPeak] as Number, 0, "still dynamic peak matches independent oracle");
    return true;
}

(:test)
function testSyntheticSmoothMotionVector(logger as Test.Logger) as Boolean {
    var x = [
        0,
        139,
        270,
        383,
        473,
        533,
        559,
        550,
        507,
        431,
        329,
        206,
        70,
        -70,
        -206,
        -329,
        -431,
        -507,
        -550,
        -559,
        -533,
        -473,
        -383,
        -270,
        -139
    ] as Array<Number>;
    var y = [
        308,
        298,
        270,
        225,
        165,
        95,
        19,
        -58,
        -131,
        -196,
        -249,
        -286,
        -306,
        -306,
        -286,
        -249,
        -196,
        -131,
        -58,
        19,
        95,
        165,
        225,
        270,
        298
    ] as Array<Number>;
    var z = [
        1000,
        1059,
        1104,
        1123,
        1111,
        1072,
        1015,
        955,
        905,
        879,
        883,
        916,
        969,
        1031,
        1084,
        1117,
        1121,
        1095,
        1045,
        985,
        928,
        889,
        877,
        896,
        941
    ] as Array<Number>;
    var result = Motion.features(x, y, z);
    Test.assertEqualMessage(result[:rms] as Number, 1100, "smooth RMS matches independent oracle");
    Test.assertEqualMessage(result[:peak] as Number, 1218, "smooth peak matches independent oracle");
    Test.assertEqualMessage(result[:zc] as Number, 4, "smooth crossings match independent oracle");
    Test.assertEqualMessage(
        result[:dynamicRms] as Number,
        460,
        "smooth dynamic RMS matches independent oracle"
    );
    Test.assertEqualMessage(
        result[:dynamicPeak] as Number,
        559,
        "smooth dynamic peak matches independent oracle"
    );
    return true;
}

(:test)
function testSyntheticIrregularMotionVector(logger as Test.Logger) as Boolean {
    var x = [
        -426,
        -412,
        -356,
        -258,
        -119,
        53,
        248,
        257,
        386,
        509,
        612,
        683,
        711,
        687,
        348,
        282,
        176,
        33,
        -137,
        -325,
        -284,
        -402,
        -510,
        -595,
        -646
    ] as Array<Number>;
    var y = [
        322,
        340,
        315,
        241,
        123,
        -32,
        -207,
        -216,
        -317,
        -396,
        -438,
        -430,
        -367,
        -248,
        -46,
        70,
        203,
        335,
        447,
        521,
        298,
        289,
        236,
        140,
        6
    ] as Array<Number>;
    var z = [
        1000,
        1087,
        1159,
        1180,
        1134,
        1027,
        893,
        875,
        844,
        869,
        953,
        1071,
        1180,
        1237,
        1120,
        1059,
        960,
        858,
        794,
        800,
        936,
        1015,
        1106,
        1173,
        1184
    ] as Array<Number>;
    var result = Motion.features(x, y, z);
    Test.assertEqualMessage(result[:rms] as Number, 1152, "irregular RMS matches independent oracle");
    Test.assertEqualMessage(result[:peak] as Number, 1436, "irregular peak matches independent oracle");
    Test.assertEqualMessage(result[:zc] as Number, 5, "irregular crossings match independent oracle");
    Test.assertEqualMessage(
        result[:dynamicRms] as Number,
        533,
        "irregular dynamic RMS matches independent oracle"
    );
    Test.assertEqualMessage(
        result[:dynamicPeak] as Number,
        820,
        "irregular dynamic peak matches independent oracle"
    );
    return true;
}

(:test)
function testSyntheticSpikeMotionVector(logger as Test.Logger) as Boolean {
    var x = [
        0,
        162,
        313,
        445,
        549,
        618,
        649,
        638,
        588,
        501,
        382,
        239,
        4200,
        -81,
        -239,
        -382,
        -501,
        -588,
        -638,
        -649,
        -618,
        -549,
        -445,
        -313,
        -162
    ] as Array<Number>;
    var y = [
        300,
        291,
        263,
        219,
        161,
        93,
        19,
        -56,
        -128,
        -191,
        -243,
        -279,
        -900,
        -298,
        -279,
        -243,
        -191,
        -128,
        -56,
        19,
        93,
        161,
        219,
        263,
        291
    ] as Array<Number>;
    var z = [
        1000,
        1077,
        1135,
        1160,
        1145,
        1094,
        1020,
        941,
        877,
        843,
        848,
        890,
        1600,
        1040,
        1110,
        1152,
        1157,
        1123,
        1059,
        980,
        906,
        855,
        840,
        865,
        923
    ] as Array<Number>;
    var result = Motion.features(x, y, z);
    Test.assertEqualMessage(result[:rms] as Number, 1438, "spike RMS matches independent oracle");
    Test.assertEqualMessage(result[:peak] as Number, 4583, "spike peak matches independent oracle");
    Test.assertEqualMessage(result[:zc] as Number, 6, "spike crossings match independent oracle");
    Test.assertEqualMessage(result[:dynamicRms] as Number, 994, "spike dynamic RMS matches independent oracle");
    Test.assertEqualMessage(
        result[:dynamicPeak] as Number,
        4168,
        "spike dynamic peak matches independent oracle"
    );
    return true;
}
